config/routes.rb
Vividaura::Application.routes.draw do
  resources :tracks do
    resources :comments, :except => [:index, :update]
    member do 
      get :queue
  end
    resources :stems do
      put :approve
    end
  end

  resources :activities, :controller => "public_activity"

  resources :relationships, only: [:create, :destroy]

  devise_for :users

  get 'users/:id/following' => 'users#following', as: :users_following
  get 'users/:id/followers' => 'users#followers', as: :users_followers

  get 'users/:id' => 'users#show', as: :user
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'

  root 'pages#home'

 

  

end

app/models/track.rb
class Track < ActiveRecord::Base
	include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }, 
	  :on => {:destroy => proc {|model, controller| model.activities.delete_all }},
	  :only => [:create]

	has_many :stems, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	has_many :users, through: :collabs
	has_many :collabs, :dependent => :destroy
	belongs_to :user

	accepts_nested_attributes_for :stems
	accepts_nested_attributes_for :collabs, :allow_destroy => true, :update_only => true, :reject_if => lambda { |c| c[:email].blank? }
	validates :user_id, presence: true

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  include ActionController::Live
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :set_track, only: [:show, :edit, :update, :destroy, :queue]
  before_filter :ensure_current_user_is_owner, only: :queue

  def index
    @tracks = Track.where(:is_private => false).order('created_at desc')
  end

  # Public View
  def show
    @approved_stems = @track.stems.where(:approved => true).order('created_at desc')
    @comment = Comment.new
    @comments = @track.comments.order("created_at desc")
  end

  # Private queue
  def queue 
    @disapproved_stems = @track.stems.where(:approved => false).order('created_at desc')

  end

  def new
  	@track = current_user.tracks.new
    @track.stems.build
  end

  def edit
    @track = current_user.tracks.find(params[:id])

  end

  def create
    @track = current_user.tracks.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: "Track created."}
      else
        format.html { render action: 'new'}
      end
    end
  end

  def update
    @track = current_user.tracks.find(params[:id])
  	respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @track = current_user.tracks.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html {redirect_to tracks_url}
    end
  end

  private

  def set_track
    @track = Track.find(params[:id])
  end

  def ensure_current_user_is_owner
    if current_user != @track.user
      redirect_to tracks_url, :alert => 'Fuck off.'
    end
  end

  def track_params
    # params[:track][:stems_attributes]['0'][:user_id] = current_user.id
    # params[:track][:stems_attributes]['0'][:approved] = true
    params.require(:track).permit(:title, :description, :bpm, :is_private, :stems_attributes => [:audio, :title, :user_id, :approved], :collabs_attributes =>[:email, :id, :_destroy])
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_collab_fields.html.erb
<div class="nested-fields">
<%= f.label :email, "Enter Users Email" %>
<%= f.text_field :email  %>
<%= link_to_remove_association "remove collaborator", f %>
</div>

app/views/tracks/edit.html.erb
<h2>Editing track</h2>

<%= form_for @track do |f| %>
	<% if @track.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@track.errors.count, "error") %> prohibited this post from being saved:</h2>
	    <ul>
	    <% @track.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_field :description %>	

	<%= f.label :bpm %>
	<%= f.text_field :bpm %>

	<%= f.label :is_private, "Private?" %>
	<%= f.check_box :is_private %>

	<%= @track.collabs.count %>
	<% if @track.is_private? %>
		<div id="collabs">
			<%= f.fields_for :collabs do |collab| %>
				<%= render 'collab_fields', f: collab %>
			<% end %>
			<p><%= link_to_add_association 'add collaborator', f, :collabs %></p>
		</div>
	<% end %>

	<div class="form-actions">
		<%= f.button :submit, class: 'btn btn-primary' %>
	</div>
<% end %>

<%= link_to 'Show', @track %>

app/views/tracks/index.html.erb
<h1>All tracks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>BPM</th>
      <th>Users</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>

        <td><%= track.title %></td>
        <td><%= track.description %></td>
        <td><%= track.bpm %></td>
        <td><%= link_to track.user.username, track.user %></td>
        <td><%= link_to 'Show', track %></td>
        <% if current_user == track.user %>
          <td><%= link_to 'Edit', edit_track_path(track) %></td>
          <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h2>New Track</h2>

<%= form_for @track do |t| %>
<%= render "shared/form_errors", :object => @track %>

	<%= t.label :title %>
	<%= t.text_field :title %>
	<%= t.label :description %>
	<%= t.text_field :description %>
	<%= t.label :bpm %>
	<%= t.text_field :bpm %>
	<%= t.label :is_private, "Private?" %>
	<%= t.check_box :is_private %>

	<h2>Upload Stem: </h2>
	<%= t.fields_for :stems do |stems_form| %>
		<%= stems_form.label :title %>
		<%= stems_form.text_field :title %>
		<p><%= stems_form.file_field :audio %></p>
		<%= stems_form.hidden_field :user_id, :value => current_user.id %>
		<%= stems_form.hidden_field :approved, :value => true %>
	<% end %>

	<div class="form-actions">
		<%= t.button :submit, class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/tracks/queue.html.erb
<% if !@disapproved_stems.blank? %>

<% @disapproved_stems.each do |stem| %>
	<h3><%= stem.title %></h3>
	<p>
		<audio controls="controls" class="audio_player">
			<source src= <%= stem.audio.url %> type="audio/mpeg">
		</audio>
		
<%= link_to "Approve", track_stem_approve_path(@track, stem), :method => :put, class: "btn btn-primary" %>
	</p>
 Uploaded at: <%= format_date(stem.created_at) %> <strong>by: <%= link_to User.find(stem.user_id).username, User.find(stem.user_id) %></strong>|
	<%= link_to "Delete Stem", track_stem_path(@track, stem), method: :delete, data: {confirm: 'Are you sure you want to delete this stem?'} %>

<% end %>

<% else %>

<h1>Currently no queued tracks.</h1>

<% end %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>
<% if @track.is_private? == false || @track.collabs.map(&:user).include?(current_user) || current_user == @track.user %>
	<div class="row-fluid">
		<div class="span4 well well-small">
			<p>
				<%= link_to 'Add Stem', new_track_stem_path(@track) %> | 
				<strike><%= link_to "Download All", "#" %></strike> | 

				<% if current_user == @track.user %>
					<%= link_to "Queue", queue_track_path %>
				<% end %>
			</p>


			<p>
			  <strong>Title:</strong>
			  <%= @track.title %>
			</p>

			<p>
			  <strong>Description:</strong>
			  <%= @track.description %>
			  <strong><p>BPM: <%= @track.bpm %></p></strong>
			</p>

			<p>
				<strong>Track owner:</strong>
			<p>
				<img src=<%=@track.user.avatar.thumb.url%>>&nbsp;<%= link_to @track.user.username, @track.user %></p>
			</p>

			<% if current_user == @track.user %>
				<%= link_to 'Edit Track', edit_track_path(@track) %> |
				<%= link_to 'Delete Track', @track, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>

		</div>

		<div class="span6 well well-small">
			<p>
				<button id="play_all">Play/Pause All</button>
				<button class="reset_transient">Reset Master Playhead</button>
			</p>

			<div class="track_space">

				<% @approved_stems.each do |stem| %>
					<h4 class="stemtitle"><%= stem.title %></h4><%= format_date(stem.created_at) %>
					<p>
						<audio controls="controls" class="audio_player">
							<source src= <%= stem.audio.url %> type="audio/mpeg">
						</audio>
					</p>
					<p>
						Uploaded by: <%= link_to stem.user.username, stem.user %> |
						<i class="icon-download"></i><%= link_to "Download", stem.audio.url %> |
						<% if current_user == @track.user %>
							<%= link_to "Delete Stem", track_stem_path(@track, stem), method: :delete, data: {confirm: 'Are you sure you want to delete this stem?'} %>
						<% end %>
					</p>
				<% end %>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span12 well well-small">
			<h3>Comments</h3>
			<%= render 'comments/show' %>
			<p><%= render 'comments/form' %></p>
		</div>
	</div>


	<% else %>

	No access

<% end %>