config/routes.rb
Vividaura::Application.routes.draw do
  resources :tracks do
    resources :comments, :except => [:index, :update]
    member do 
      get :queue
  end
    resources :stems do
      put :approve
    end
  end

  resources :activities, :controller => "public_activity"

  resources :relationships, only: [:create, :destroy]

  devise_for :users

  get 'users/:id/following' => 'users#following', as: :users_following
  get 'users/:id/followers' => 'users#followers', as: :users_followers

  get 'users/:id' => 'users#show', as: :user
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'

  root 'pages#home'

 

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: ->(controller, model) { controller && controller.current_user },
	  :on => {:destroy => proc {|model, controller| model.activities.destroy_all }},
	  :only => [:create]
	belongs_to :track
	belongs_to :user
	validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include ActionController::Live
	before_filter :user_signed_in?
	before_filter :load_tracks

def show
	@comment = Comment.find(params[:id])
end

def new
	@comment = current_user.comments.new
end

def edit
	@comment = current_user.comments.find(params[:id])
end

def create
  @comment = current_user.comments.new(comment_params)
  respond_to do |format|
    if @comment.save
      format.html { redirect_to @track, notice: "Comment created."}
    else
      format.html { redirect_to @track, alert: @comment.errors.full_messages }
    end
  end
end

def update
end

def destroy
  @comment = current_user.comments.find(params[:id])
  @comment.destroy
  respond_to do |format|
    format.html {redirect_to @track}
  end
end

private

def load_tracks
@track = Track.find(params[:track_id])
end

def set_comment
  @comment = Comment.find(params[:id])
end

def comment_params
	params[:comment][:track_id] = params[:track_id]
  params.require(:comment).permit(:text, :user_id, :track_id)
end

end

app/helpers/comments_helper.rb
module CommentsHelper
	def format_date(time)
	
		time.in_time_zone("Eastern Time (US & Canada)").strftime("%B %e %Y - %l:%M %p")
	end
end

app/views/comments/_form.html.erb
<%= form_for([@track, @comment]) do |f| %>
	<%= render "shared/form_errors", :object => @comment %>
<%= f.label :comment %>
<%= f.text_field :text %>
<%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/comments/_show.html.erb
<% @comments.each do |comment| %>

</br>
<img src=<%=comment.user.avatar.thumb.url%>>&nbsp;<%= link_to comment.user.username, @track.user %>
<%= format_date(comment.created_at) %>


<% if current_user == comment.user %>
	<%= link_to "Destroy", track_comment_path(@track, comment), method: :delete, data: {confirm: 'Are you sure you want to delete this comment?'} %>
	<p class="bubble"><%= comment.text %></p></br></br>
	<% end %>

<% end %>