config/routes.rb
Vividaura::Application.routes.draw do
  resources :tracks do
    resources :comments, :except => [:index, :update]
    member do 
      get :queue
  end
    resources :stems do
      put :approve
    end
  end

  resources :activities, :controller => "public_activity"

  resources :relationships, only: [:create, :destroy]

  devise_for :users

  get 'users/:id/following' => 'users#following', as: :users_following
  get 'users/:id/followers' => 'users#followers', as: :users_followers

  get 'users/:id' => 'users#show', as: :user
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'

  root 'pages#home'

 

  

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :login
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  validate :sanitize_username, :on => :create
  validates :username, uniqueness: true
  validates :username, presence: true


  has_many :tracks, :dependent => :destroy
  has_many :stems
  has_many :comments
  has_many :relationships, foreign_key: "follower_id", :dependent => :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name: "Relationship",
                                    :dependent => :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  has_many :track_collabs, through: :collabs, :class_name => "Track"
  has_many :collabs, :dependent => :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private

  def sanitize_username
  	self.username = username.downcase.gsub(" ", "")
  end

  def confirmation_required?
    true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: @user, owner_type: "User").page(params[:page]).per_page(20)
  end

  def followers
  	@user = User.find(params[:id])
  	@users = @user.followers
  end

  def following
    @user = User.find(params[:id])
  	@users = @user.followed_users
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div>
  	<%= f.hidden_field :followed_id %>
  </div>
  
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
  <a href="<%= users_following_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= users_followers_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/followers.html.erb
<div class="row-fluid">
	<div class="span6 well">
<% @user ||= current_user %>
<% @user.followers.each do |f| %>

<h3><img src=<%=f.avatar.thumb.url%>> <%= link_to f.username, user_path(f.id) %></h3>

<% end %>
</div>
</div>

app/views/users/following.html.erb
<div class="row-fluid">
	<div class="span6 well">
<% @user ||= current_user %>
<% @user.followed_users.each do |f| %>

<h3><img src=<%=f.avatar.thumb.url%>> <%= link_to f.username, user_path(f.id) %></h3>

<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="span4 well well-small">
    <%= image_tag @user.avatar.thumb.url %>

    <h1 class="user_profile_name">
      <%= @user.username %>
    </h1>

  	<p class="stats">
      <%= render 'stats' %>
    </p>

    <% if user_signed_in? %>
    <% unless current_user.id.to_s == params[:id] %>
      <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
      <% else %>
        <%= render 'follow' %>
      <% end %>
    <% end %>
    <% end %>

<p>------------------------------------</p>


    <h3>Created Tracks</h3>
    <% @user.tracks.each do |t| %>
      <p>
      <%= link_to t.title, t %>
      </p>
    <% end %>
  </div>

  <div class="span8 well">
    <%= render 'public_activity/stemfeed' %>

  </div>


  